// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = {
    Cache: require('./cache'),
    Redis: function() {
      return require('./redis');
    },
    Memcached: function() {
      return require('./memcached');
    }
  };

}).call(this);
