// Generated by CoffeeScript 1.6.3
(function() {
  var expireTime, redis;

  redis = require(redis);

  module.exports = Interface;

  Interface.init = function(options) {
    return this.client = redis.createClient(options);
  };

  Interface.write = function(model, key, value, next) {
    var client;
    client = this.client;
    return client.set([key, value], function(err, result) {
      if (err) {
        redis.print(err, result);
      }
      next(err, result);
      return client.expire(key, expireTime(model, function(err) {
        if (err) {
          return redis.print(err, result);
        }
      }));
    });
  };

  Interface.read = function(key, next) {
    return client.get(key, function(err, result) {
      if (err) {
        redis.print(err, result);
      }
      if (err) {
        return next(false);
      } else {
        return next(err, result);
      }
    });
  };

  expireTime = function(model) {
    return model.get('expire' || 1000 * 30);
  };

}).call(this);
